### ISSUE TITLE
DOMReadOnlyRect or DOMRectReadOnly

### ISSUE THREAD

**Issue by ghost** [WICG/ResizeObserver#12]
Hi,

I think there is a typo in the IDL. In ResizeObserverEntry, you write 'readonly attribute DOMReadOnlyRect contentRect;'. Did you actually mean 'readonly attribute DOMRectReadOnly contentRect;'? I think the correct name for the interface is DOMRectReadOnly (https://drafts.fxtf.org/geometry-1/#domrectreadonly).

**Comment by atotic** [comment]
Thanks!
