### ISSUE TITLE
Clarification needed on `target.depth`

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#13]
The ResizeObserver has some discussion of a `depth` concept, which seems to chiefly come into play via comparisons to `target.depth`, e.g. here:

> If `target.depth` is greater than depth then add observation to `activeTargets`
> ...and here:
> Set `shallowestTargetDepth` to `observation.target.depth` if `observation.target.depth` < `shallowestTargetDepth`

Here, I believe `target` is an `Element`.  I'm not aware of `depth` being a member-variable on the `Element` API, though, so I don't know what this spec-text is actually referring to.  (`depth` isn't mentioned in the `Element` definition at https://dom.spec.whatwg.org/#element , for example)

@atotic , could you clarify what "depth" means here, and where it's defined? (and whether there's actually expected to be anything like it on the `Element` interface)

**Comment by atotic** [comment]
You are correct, the DOM standard does not specify `depth` as member-variable of Element or Node. The term `depth` is commonly used in the development community to mean the length of parent-traversal path from Element to the root of the DOM tree (Document).

Ideally, the term would be defined in the DOM standard. Until this happens, I'll define it inside my spec as an algorithm.

**Comment by dholbert** [comment]
Thanks!

(Looks like that commit updated the bikeshed file, but the HTML still needs to be regenerated to pick up the update. I assume you're already planning on doing that separately, but I'm mentioning it here in case that was an oversight.)

**Comment by dholbert** [comment]
Also: you've replaced one `target.depth` reference, but there are two other references to `target.depth` which need a similar update. Both references are on one line (line 382 of the bikeshed source right now) -- quote:

> To broadcast active observations for a |document|,
> [...]
> 1. Set |shallowestTargetDepth| to |observation|.{{ResizeObservation/target}}.depth if |observation|.{{ResizeObservation/target}}.depth < |shallowestTargetDepth|

https://github.com/WICG/ResizeObserver/blob/305c360bb2445878ca1347fc0ebeeb4703eafe04/index.bs#L382

**Comment by atotic** [comment]
You are reading this spec more closely than I. Thanks :)

**Comment by dholbert** [comment]
Sure! Thanks for being responsive! :)

(We've got an intern (@fariskhi ) working on this in Firefox, and my recent questions have mostly prompted by questions from him & by other things I'm running across when looking for answers.)

**Comment by atotic** [comment]
I've added some test cases to this repo. They might be useful when implementing.
