### ISSUE TITLE
Clarify the idea behind & the termination characteristics of the `depth`-based cycling

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#15]
The ResizeObserver spec recently got a node-depth-based technique to avoid cycles.  The algorithms around `depth` seem pretty clearly spelled out, but a few things were not at all clear to me up front (in part because the depth-handling is split across the spec).

I have some questions and possible-answers below.  It would help to spell out the correct answers to my questions in some explanatory prose in the spec, to give the reader a bit of a foundation for what the algorithms are actually trying to achieve.  Otherwise, the `depth` algorithms are just manipulating nodes with no clear goal.

**My questions when reading the new `depth` stuff the first few times:**
 (a) How do we know the `depth`-based cycling actually terminates? (That's one of the key expected outcomes of this new `depth`-based complexity, I expect.)
 (b) What is the point of caring about `depth` here? (what does it buy us, aside from a convenient means to a terminating algorithm)

**My guesses at answers:**
I suspect the answer to (a) is: "each cycle only cares about things that are strictly deeper than the previous cycle". For a static tree, I can see how that would be guaranteed to terminate. However, if your resizeObserver callback adds a child & registers a resizeObserver callback on that child, it still seems like a page could go on looping forever (throwing progressively-deeper children out ahead of itself). This is perhaps a bit pathological, but if the point of this depth stuff is to avoid infinite-looping (and protect developers from shooting themselves in the foot), a lack-of-termination-guarantee seems like a problem...

I suspect the answer to (b) is: "`depth` cycling is useful because it means when a parent responds to a resize, its children get a chance to re-run their resizeObserver callbacks with the parent's new size".  That makes some sense, I think...

**Comment by atotic** [comment]
a) you are correct in that depth does not guarantee termination if an infinite number of children is added. In that case, out of memory condition will provide termination. 
b) we needed some kind of limit, and depth had nicer properties than other options. See #7 for detailed discussion.

**Comment by dholbert** [comment]
Thanks for clarifying!

So, my point in filing this issue was that the spec doesn't give any sort of hint about the motivation for this `depth` stuff right now.  If you could add something like that, I think it'd prevent confusion (and give a framework/motivation for understanding the algorithms) in future spec readers.

E.g. now that I've read #7, this specific text was super-helpful to me in clarifying this:

> Depth limit works by narrowing down the set of nodes allowed to receive notifications in each iteration.
> Depth limit can iterate at most 'depth of DOM tree' times.
> A nice property of depth limit is that if a resizeHandler generates new notifications, only its children get to handle them right away.

If it'd be possible to work some version of that ^ explanatory text in to the spec, that would be great!

**Comment by atotic** [comment]
The spec says:

> Infinite loop is prevented by shrinking the set of nodes that can notify at every iteration. In each iteration, only nodes deeper than the shallowest node in previous iteration can notify.

I've thought that this is 'good enough'. In most specs I've read, the details of 'why' are fairly brief. And that is why I'll keep discussion summaries as open bugs, so others can see the details.

**Comment by dholbert** [comment]
Thank you, I missed that chunk. Sorry for the oversight.

(In particular, I did find-in-page for `depth` and didn't find anything but algorithms.  It might be worth wordsmithing the term `depth` somewhere into that prose, so that people like me will be able to find it easier when wanting to learn more about the `depth`-based algorithms.)
