### ISSUE TITLE
How do we observe inline elements?

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#19]
QUESTION: If a ResizeObserver is registered for a `<div>`, and that `<div>` changes from `display:block` to `display:inline`, should the observer's callback function be invoked for the resulting relayout?  (And if the callback is invoked, what contentRect would be used?)

I think the answer is "no", because when the style change happens, the element becomes a non-replaced inline element, and the spec explicitly says "observations do not fire for non-replaced inline Elements".

On the other hand, if the element changes from `display:inline` back to `display:block`, then the callback _would_ fire, because the element would then be block-level at the time where we're deciding whether to fire the callback.

This seems awkwardly asymmetrical, though.  Am I understanding the spec correctly here?

**Comment by dholbert** [comment]
It kind of seems like this should behave the same as when the element changes between `display:block` and `display:none` (and the spec is clearer about what's supposed to happen there).  Is it intended that these behave similarly?

If that is the intention, the spec definitely needs clarification on that point -- right now, the spec seems to _explicitly_ differentiate between those scenarios:

> - observation will fire when watched Element display gets set to hidden. _[sic: [this means to say `none`, not `hidden`](https://github.com/WICG/ResizeObserver/issues/20)]_
> - observations do not fire for non-replaced inline Elements.

Right now, this spec text pretty clearly indicates that the answer to my "QUESTION" would be "No, don't fire", because at the moment that we're deciding whether to issue the notification (after the restyle/layout) we're dealing with a non-replaced inline element, for which this spec-text is explicitly saying "observations do not fire".

SO: perhaps that that last bullet point needs to be clarified to make the intent a bit clearer -- e.g. maybe it wants to say:

> - observations do not fire for changes to a non-replaced inline Element's size, or for such an Element's insertion/removal (though they do fire when a non-replaced element's computed `display` changes from `block` to `inline`).

@atotic , what do you think?

**Comment by atotic** [comment]
Your initial reading of the spec was correct, we do not fire notifications for inline elements.
I understand that switching from inline to block and back is awkward.

I would like to leave the spec as is because doing anything when element is inline gets messy:
- what rect is display:inline observing? Element could change display from block to inline, and not change size.
- implementation:  You'd have to keep state of what display value used to be in order to fire.

PS: right now, working on chrome bug with absolute positioning and display:inline. We would have been better off it it was not allowed.

**Comment by dholbert** [comment]
> what rect is display:inline observing [ ...]  Element could change display from block to inline, and not change size.

(The same is true of `display:none`, to some extent -- you _could_ have a zero-sized element with `display:block` which becomes `display:none` -- I take it that shouldn't trigger a notification, since its size isn't changing?  The same could be true for inline, I expect.)

But, point taken, and this is fine with me.

> PS: right now, working on chrome bug with absolute positioning and display:inline. We would have been better off it it was not allowed. 

(Just to be clear, absolute positioning should convert a `display:inline` element to have `display:block` in its computed style, per step 2 of https://drafts.csswg.org/css2/visuren.html#dis-pos-flo -- so I expect resize observers should definitely fire for `<div style="position:absolute; display: inline">`.  Let me know if your understanding is different...)

**Comment by que-etc** [comment]
> PS: right now, working on chrome bug with absolute positioning and display:inline. We would have been better off it it was not allowed.

Oh, I've thought that this is the expected behavior. I've even got this case covered by tests.:)

**Comment by atotic** [comment]
> (The same is true of display:none, to some extent -- you could have a zero-sized element with display:block which becomes display:none -- I take it that shouldn't trigger a notification, since its size isn't changing? The same could be true for inline, I expect.)

Correct. No notification if size 0,0 element goes to display:none.

> Just to be clear, absolute positioning should convert a display:inline element to have display:block in its computed style, per step 2 of https://drafts.csswg.org/css2/visuren.html#dis-pos-flo -- so I expect resize observers should definitely fire for <div style="position:absolute; display: inline">. Let me know if your understanding is different...)

Got that. Mine is a different bug, not related to ResizeObserver. It involves a absolutely positioned block whose containing block is display:inline.....

**Comment by fariskhi** [comment]
I just noticed the ResizeObserver implementation in Chromium right now will fire the observation when an element changes from non-inline to inline.

Example:
http://jsbin.com/puxifazilo/embed?html,js,console

I'm using the build from latest Chromium repository and change 'ResizeObserver status' in RuntimeEnabledFeatures.in so I can use ResizeObserver.

I think we really need to add the test case for this to test/notify.html

**Comment by ghost** [comment]
I just noticed the ResizeObserver implementation in Chromium right now will fire the observation when an element changes from non-inline to inline.

Example:
http://jsbin.com/zoyupajaje/1/edit?html,js,console,output

I'm using the build from latest Chromium repository and change 'ResizeObserver status' in RuntimeEnabledFeatures.in so I can use ResizeObserver.

I think we really need to add the test case for this to test/notify.html

**Comment by atotic** [comment]
Filed a bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=646656

**Comment by atotic** [comment]
I've thought about this some more. You guys are starting to convince me that never delivering notification for inline elements is not the right thing to do. Arguments against 'no inline'
- block -> inline does not fire, inline -> block does. Asymmetrical
- Denis Rul's polyfill, and Chrome implementation both have the same bug: firing notifications on block -> inline. This makes me feel that 'no fire on inline' is not the natural thing for this API.

The stumbling block for firing anything on inline blocks was always the rect. Computing inline element's client rects for observation was too expensive for expected infrequent use.

What do you think about replacing:

> observations do not fire for non-replaced inline Elements.

with

> non-replaced inline Element's content rect is considered to be an empty rect located at 0,0.

This fixes:
- block->inline asymmetry
- and polyfill and Chrome's bugs. Firefox too?

I like it. It attacks the real problem with inline elements, the content rect.

**Comment by dholbert** [comment]
> non-replaced inline Element's content rect is considered to be an empty rect located at 0,0.

That sounds fine to me (and that's actually precisely what Fariskhi has implemented in his initial patch, which is how we came to notice this potential spec issue :))

Thanks for looking into this some more!

**Comment by atotic** [comment]
You guys should have just told me I was being dense, and that inline content rect should be empty. Fix coming up in a minute.

**Comment by dholbert** [comment]
Heh. That's kinda what I was getting at with "It kind of seems like this should behave the same as when the element changes between display:block and display:none" in my second comment here -- but I should have been more specific.

Thanks for fixing this!

**Comment by atotic** [comment]
Fixed.
