### ISSUE TITLE
clientWidth linking problem in spec

### ISSUE THREAD

**Issue by atotic** [WICG/ResizeObserver#2]
I am trying to use {{clientWidth}} to refer to CSSOM#clientWidth.  
I have clientWidth property declared internally on ResizeObserverEntry IDL. 
Because of this, all my {{clientWidth}} references point to an internal definition. 

Question:
What is the best way to distinguish between two definitions?

Ideally, I'd define IDL clientWidth so that the only way to refer to it would be explicit: {{ResizeObserverEntry/clientWidth}}

I've tried various variants of:
    readonly attribute float <dfn attribute lt="entryClientHeight" >clientHeight</dfn>;

**Comment by yoavweiss** [comment]
Maybe @tabatkins can help

**Comment by atotic** [comment]
Looks like clientWidth is out of the spec, so tab can rest for now.
