### ISSUE TITLE
ResizeObserver spec typo: s/hidden/none/

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#20]
The ResizeObserver spec has two copies of the phrase:

> observation will fire when watched Element display gets set to hidden.

This means to say "none", not "hidden".  ("hidden" is not a valid value for "display")

**Comment by dholbert** [comment]
(I'd issue a pull request to fix this trivial issue, but I don't have bikeshed installed/configured locally, so it's not-quite-trivial for me to generate a pull request. Hopefully @atotic doesn't mind taking/fixing this. :))

**Comment by markcellus** [comment]
:+1

**Comment by dholbert** [comment]
@atotic: thanks! But, it's not quite fixed -- there were _two_ instances of this typo (as noted in the first comment here), and f935e77 only fixed one of them.

The other one still remains, at line 317, here:
https://github.com/WICG/ResizeObserver/blob/f935e77ac9fc1e07cba025283a5a2ae7a57d9d69/index.bs#L317

(It's the only remaining instance of "hidden" in that file)

**Comment by dholbert** [comment]
Thanks!
