### ISSUE TITLE
spec needs to be clear that an unparented element (e.g. from removeChild) has depth of 1, not 0

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#21]
Consider this scenario:

> ro.observe(x);
> ...
> x.parentNode.removeChild(x); 

QUESTION: Should we fire the resize observer's callback after "x" is removed from the document?

(This scenario is actually exercised in https://github.com/WICG/ResizeObserver/blob/master/test/notify.html `test2()`, which has a comment saying "removeChild triggers notification" -- so that test is clearly _expecting_ that the answer to my question is "yes")

CURRENT (UNSATISFACTORY) ANSWER: Right now, the spec implies that we should _not_ notify in this case, i.e. it disagrees with the testcase.   (Though really, it kinda ends up depending on something undefined).

Specifically -- the spec's definition of "depth" doesn't take unparented nodes (like "x" in this case) into account, so their depth is undefined. The spec [currently says this about calculating depth](https://wicg.github.io/ResizeObserver/#calculate-depth-for-node):

> To calculate depth for node node run these steps:
> 1.  Let `p` be the parent-traversal path from `node` to enclosing `Document`.
> 2.  Return length of `p`.

And in this case where `x` has been removed, there _is no parent-traversal path from `x` to the enclosing document_. `x.parentNode` is null (whereas e.g. `document.documentElement.parentNode` does actually return the Document object)

You might say this doesn't leave anything undefined -- it seems natural to think that `x` simply has a depth of 0, since there's no parent-traversal path.  (That's what we initially decided for our WIP implementation in Firefox.)  BUT, that implies we _shouldn't notify_ for the scenario in my question above (and we'd fail notify.html as a result), because the spec basically says to ignore elements at depth=0.  Specifically, the spec requires us to look for elements to notify about [by doing the following](https://wicg.github.io/ResizeObserver/#html-event-loop):

>  set `depth` to 0
>  gather active observations at depth `depth` for Document  _(i.e. gather observations at depth 0)_

And the ["gather active observations" algorithm](https://wicg.github.io/ResizeObserver/#gather-active-observations-at-depth) only treats things that are _greater_ than `depth` as being "active":

> If targetDepth is greater than depth then add observation to activeTargets.

So any node whose depth is 0 is ignored by the algorithm, by definition. So if we want removal to trigger a notification, then unparented nodes need to be clearly defined as having a depth of 1 (not 0).

SUGGESTED CHANGE: We need to update the "depth" definition to take (newly-)unparented nodes into account, and to make it clear that they should be considered as having a depth of _1_, not 0.

**Comment by dholbert** [comment]
Note that (according to @fariskhi), Chromium's implementation does return 1 (not 0) for unparented nodes -- it [looks like this](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/observer/ResizeObservation.cpp?q=resizeobservation&sq=package:chromium&l=35):

```
unsigned depth = 0;
for (Element* parent = m_target; parent; parent = parent->parentElement())
    ++depth;
return depth;
```

If m_target has no parent, this algorithm returns 1 (not 0).

**Comment by atotic** [comment]
Would you be ok to redefine depth as:
1. Return length of p + 1

That avoids off by 1 error when traversing. Alternate, we can start traversal with depth=-1

**Comment by dholbert** [comment]
I think we should redefine `p` as the path to a root element (one with no `parentElement`), and consider the path's length to be the number of nodes traversed in that path. (Or the edges + 1; doesn't matter to me.)  That matches what Chrome's implementation does, at least -- and Firefox's WIP implementation as well, I think.  So, an unparented node would have a depth of 1, its children would have a depth of 2, etc.  (And the root `<html>` node would have a depth of 1 as well, since it's got a null `.parentElement` (despite having a non-null `.parentNode`, which is the document.))

Otherwise -- i.e. with just your suggested +1 tweak -- we're still left with things being a bit vague in a scenario where a _subtree_ is disconnected from the document, and that subtree has some descendant (say, 5 levels deep) which is being observed. In that scenario, Chrome's C++ implementation (quoted above) would return the depth of that node _within its severed/unparented subtree_ -- i.e. it'd return 5.  This still doesn't match the spec (with or without the +1 tweak) -- the old spec text says it should return 0, and your proposed spec text would say it should return 1.  (And that's all assuming that the length of a nonexistant path can be considered to be 0 rather than undefined, and I'm not sure that's obvious)

**Comment by atotic** [comment]
Fixed:
Let |p| be the parent-traversal path from |node| to a root of this element's DOM tree.

**Comment by dholbert** [comment]
Thanks! Looks like that change landed in 555986f0426ecea8e99e6eac34cd7207d6a34512.

But, I don't think that entirely fixes this -- it still leaves two things unclear:
 (1) RE "a root of this element's DOM tree" -- for a normal element in the page (one connected to the rest of the DOM), are we talking about the root _element_ (`<html>`) here, or the root _node_ (the `Document` object)? This makes a +/- 1 difference in what the algorithm returns.

(2) Does `length of p` mean number of nodes (elements) in the path, or number of edges?  As above, this makes a +/- 1 difference in what the algorithm returns.

My preference for (1) would be "root element"   (for better consistency between severed & not-severed subtrees, & because that's what we happen to have implemented everywhere). 

And for (2), we really need to either use "number of nodes", or "number of edges + 1" (which is the same thing really).  Otherwise, as I originally reported here, an unparented node would have a depth of 0 and would get skipped by the gather-active-observations-deeper-than-depth-0 algorithm elsewhere in the spec.

**Comment by atotic** [comment]
New text:
    1. Let |p| be the parent-traversal path from |node| to a root Element of this element's DOM tree.
    2. Return number of nodes in |p|.

**Comment by dholbert** [comment]
That sounds great. Thanks!
