### ISSUE TITLE
ResizeObserver test incorrectly depends on Chrome's img-with-no-src-attribute quirk

### ISSUE THREAD

**Issue by dholbert** [WICG/ResizeObserver#23]
One of the ResizeObserver tests accidentally depends on a Chrome rendering quirk.

Specifically, "observe.html" has an `<img>` element that lacks a valid `src` attribute:

```
<img id="target3" style="width:100px;height:100px;">
```

https://github.com/WICG/ResizeObserver/blob/e44839a73ebf43421669ea8abba27f098bfa7041/test/observe.html#L8

In Chrome, this <img> still behaves like a replaced element (and therefore fires observations).  In Firefox, it behaves like an empty non-replaced inline element (e.g. it's just like an empty `<span>` -- so it doesn't respect its width/height and it doesn't fire observations, just as would happen for an empty `<span>`).

Firefox's behavior is actually what the HTML spec requires, as discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=851048#c8 and earlier comments there.  (though I think this is a long-time rendering difference between WebKit/Blink and Firefox and maybe WebKit/Blink engineers might have a different understanding -- I'm not sure)

Anyway -- setting that difference aside, we should fix the test so that it doesn't accidentally depend on either behavior -- we should give it a valid `src="..."` attribute so that is definitively a replaced element and will therefore definitely exercise the spec-requirement that replaced elements fire resize observations.

**Comment by dholbert** [comment]
To avoid needing a gross data-encoded PNG or a one-off helper image file, how about we just use a trivial SVG image document?

I sanity-checked that Gecko, Blink, WebKit, & Edge all support data-URI-encoded SVG documents, using this testcase (lime means it worked): https://jsfiddle.net/ehdbtuu4/

**Comment by atotic** [comment]
Thanks for the report, and the fix.
