### ISSUE TITLE
Spec: make ResizeObserverEntry private

### ISSUE THREAD

**Issue by atotic** [WICG/ResizeObserver#35]
ResizeObserverEntry constructor should not be publicly accessible.

https://bugs.chromium.org/p/chromium/issues/detail?id=674520

**Comment by RByers** [comment]
Aren't there scenarios where some library may want to synthesize these?  Filed https://github.com/w3ctag/design-principles/issues/51 to discuss the general principle.

**Comment by atotic** [comment]
I had no strong reasons for not including the constructor, it the was the general rule: "do not write code you won't use". 
If there is a webapi rule "constructors are exposed by default", I am happy to implement it.

**Comment by tabatkins** [comment]
Yes, there is a general rule that constructors should be available unless there's good reasons to avoid them (for example, if a valid object requires private browser state, which the user can't reasonably access).
