### ISSUE TITLE
Error in ResizeObserver/#html-event-loop, missing paint step.

### ISSUE THREAD

**Issue by trusktr** [WICG/ResizeObserver#36]
The spec at https://wicg.github.io/ResizeObserver/#html-event-loop is missing the "paint" step. When does the browser paint?

**Comment by trusktr** [comment]
I meant, in the last part:

1. recalc styles
1. update layout
1. set depth to 0
1. gather active observations at depth depth for Document
1. repeat while (document has active observations)
    1. set depth to broadcast active observations
    1. recalc styles
    1. update layout
    1. gather active observations at depth depth for Document
1. if Document has skipped observations then deliver resize loop error notification

Should it need to be

1. recalc styles
1. update layout
1. set depth to 0
1. gather active observations at depth depth for Document
1. repeat while (document has active observations)
    1. set depth to broadcast active observations
    1. recalc styles
    1. update layout
    1. gather active observations at depth depth for Document
1. if Document has skipped observations then deliver resize loop error notification
1. **paint**

?

**Comment by atotic** [comment]
Thanks for noticing this.
