### ISSUE TITLE
Resize observation for an outermost <svg> element

### ISSUE THREAD

**Issue by fsoder** [WICG/ResizeObserver#39]
An outermost `<svg>` element [1] will have a CSS layout box, and in most cases I think it would make sense to "observe" changes to the CSS layout box. (On the outermost `<svg>`, the CSS layout box and the bounding box can change independently of each other.)

[1] https://svgwg.org/svg2-draft/struct.html#TermOutermostSVGElement

**Comment by atotic** [comment]
My preference is to keep things simple, and for specification to remain as is. But I do not have much real-world SVG experience.

Do you have a convincing example of where observing layout box would be preferable?

**Comment by fsoder** [comment]
Any compelling example for a HTML element could easily be converted to an equally compelling example for an `<svg>`. Like replacing the `<div id="menu">` in the spec example (not that it is a very compelling, or for that matter convincing, example) with an `<svg id="menu">` (adjusting children as needed.)

**Comment by atotic** [comment]
To observe changes to `<svg>.layoutBox`, why not wrap it inside a `<div>` and observe the div?
