### ISSUE TITLE
What size to observe?

### ISSUE THREAD

**Issue by atotic** [WICG/ResizeObserver#4]
I'd like to revisit the question: "What size to observe?"

There are two main use cases we are optimizing for:
1. `responsive-menu` : changes from menu with text to a burger icon when narrow.
   - `responsive-menu` hides/shows/resizes existing elements upon resize
2. `tiled-map`: fills its entire content area with little `<div>`s
   - `tiled-map` adds/removes/resizes divs upon resize, and fills the entire parent element.

The original observed size was [clientWidth](https://www.w3.org/TR/cssom-view-1/#dom-element-clientwidth). 

It was picked because it matched content box size better than any other Element's width properties:

clientWidth is defined as:

> - If the element has no associated CSS layout box or if the CSS layout box is inline, return zero.
> - If the element is the root element and the element’s node document is not in quirks mode, or if the element is the HTML body element and the element’s node document is in quirks mode, return the viewport width excluding the size of a rendered scroll bar (if any).
> - Return the width of the padding edge excluding the width of any rendered scrollbar between the padding edge and the border edge, ignoring any transforms that apply to the element and its ancestors.
> - Returned value is rounded. Rounding algorithm depends on location and size.

In practice, using clientWidth for size observation has several undesirable properties:
1. spurious notifications because of rounding: rounding depends on location, and just moving the element without changing its size can cause rounded clientWidth to change.
2. double notifications when box shrinks. This happens because:
   - box shrinking might cause a scrollbar to appear
   - clientWidth reported causes Element to reposition its children so scrollbar is no longer necessary
   - hiding of the scrollbar causes clientWidth to change
   - which triggers second notification. The new clientWidth is a bit larger than the old one.
   - the workaround is for authors to decare overflow:hidden.
3. hinders maximally efficient implementation in Chrome. We have to **poll** for size changes because clientWidth depends on frameSize, borderWidths, and scrollbar. Most efficient implementation would be a **push**, pushing Elements when observed properties change. For complexity reasons, only changes to frameSize can be trapped.
## Our options
1. clientWidth as float
   pros: solves problem 1, well defined cross-browser behavior
   cons: does not solve 2.
2. modified clientWidth as float, do not exclude scrollbar width. 
   pros: solves 1, and 2. Plays well when positioning absolute elements, they are relative to padding box.
   cons: it is no longer clientWidth, but paddingEdgeWidth. Messaging this is harder than "clientWidth as float".
3. border box
   pros: solves 1 and 2 and possibly 3
   cons: does not play well with positioned elements, messaging....

My favorite is option  2), clientWidth without scrollbar, because it is performant. I dislike standards that work "unless". 1) is ok, but double notification on shrink bugs me.

@bfgeek

**Comment by esprehn** [comment]
The spec doesn't have to listen to a property defined on Element, we can just define that it observes some computed value of what we think is important. We don't even need to talk about clientWidth.

**Comment by tabatkins** [comment]
> cons: does not play well with positioned elements, messaging....

What do you mean by this?

**Comment by atotic** [comment]
@tabatkins 

> What do you mean by this? does not play well with positioned elements, messaging....

"Does not play well with positioned elements" means that in general, if you are using ResizeObserver to position your children, observing border-box might cause problems because you will not be notified when border or padding change.

"messaging" means that since border-box length is not a property currently defined in CSS, we'd have to educate developers of its behavior.

**Comment by atotic** [comment]
we have a new proposal
