### ISSUE TITLE
ResizeObserver for iframed content

### ISSUE THREAD

**Issue by blois** [WICG/ResizeObserver#40]
Currently it is difficult to use an iframe for sandboxing dynamically sized content because there is no way to get the iframe to resize to the content.

A workaround for this is to observe changes inside of the iframe, get the desired size, then post a message to the parent window to resize the iframe. It would be great if ResizeObserver could fill this role.

The issue with ResizeObserver today is that when content is removed from the body of an iframe it never generates a callback that the layout height has shrunk.

**Comment by atotic** [comment]
Can you give me a code example?

**Comment by blois** [comment]
Simple repro: http://peteblois.github.io/tmp/resize_observer/index.html

The goal is that the iframe should always be sized to the content- never larger and never have scrollbars.

Note that I added another case in there as well which is an inline element with vertical padding- the size calculation for contentRect.height is different than what is used to determine the scroll height.

**Comment by atotic** [comment]
Thanks, off till early July, will be back on ResizeObserver soon after.
The "size the iframe" problem is annoying, will see if RO can help.

**Comment by blois** [comment]
Repro updated and now works as desired, no further changes needed. Excited to see this ship!

1. Added `<!DOCTYPE html>` to the iframe to use standards mode rather than quirks- with this the body size now shrinks.
2. Use `document.body.scrollHeight` to resize the iframe.
