### ISSUE TITLE
Detecting the appearance of scroll bars as another use case?

### ISSUE THREAD

**Issue by Herst** [WICG/ResizeObserver#42]
Maybe worth mentioning in the explainer that this API could also help with detecting when a vertical scroll appears and can therefore replace ugly hacks such as listening on the resize of an iframe as presented e.g. in the answers to https://stackoverflow.com/questions/2175992/detect-when-window-vertical-scrollbar-appears

**Comment by Herst** [comment]
Reading comprehension fail. My bad.

**Comment by atotic** [comment]
Thanks for the example.
