### ISSUE TITLE
ResizeObservation should be a struct, not an interface

### ISSUE THREAD

**Issue by domenic** [WICG/ResizeObserver#46]
Currently ResizeObservation is a Web IDL interface. It says "This interface is not visible to Javascript", but that's false: Web IDL automatically makes it visible to JavaScript.

What you want to use here instead is a [struct](https://infra.spec.whatwg.org/#structs), plus a couple algorithms: one to create the struct, and one to determine whether the struct is active. You should not be using interfaces, attributes, and methods.

**Comment by foolip** [comment]
I came across this in https://github.com/w3c/web-platform-tests/pull/9756. Since it's in IDL, it'll end up in web-platform-tests idlharness.js tests using the automated pipeline that @mdittmer and @lukebjerring are working on.

**Comment by lukebjerring** [comment]
https://github.com/w3c/web-platform-tests/pull/9756
