### ISSUE TITLE
ResizeObserverEntry does not properly create the content rect

### ISSUE THREAD

**Issue by domenic** [WICG/ResizeObserver#49]
The creation of the content rect value (which needs to be stored in a slot, see #48) is not written correctly. It seems to be trying to set the public property _this_.contentRect.top, etc. But this is impossible; both contentRect, and its top property, are readonly.

You should instead say something like:

> 1. Let _rect_ be a new new DOMRectReadOnly
> 2. Set _rect_'s x coordinate to ...
> 3. Set _rect_'s y coordinate to ...
> 4. Set _rect_'s width dimension to ...
> 5. Set _rect_'s height dimension to ...
> 6. Set _this_.`[[contentRect]]` to _rect_.

where each of those things link to the appropriate concept, e.g. [x coordinate](https://drafts.fxtf.org/geometry-1/#rectangle-x-coordinate).

**Comment by atotic** [comment]
moved spec to greg and csswg
