### ISSUE TITLE
Typographical issues

### ISSUE THREAD

**Issue by domenic** [WICG/ResizeObserver#50]
> window.resize event.

There is no window.resize property. Probably you meant "the resize event on Window objects" or similar. This occurs multiple times.

> ResizeObserver

Many instances of ResizeObserver are not properly linked or monospaced. Use Bikeshed's `{{ResizeObserver}}` syntax.

> Some interesting facts about these observations:

What follows is a list of sentences. However, each starts with a lowercase letter. They should be uppercase.

> IntersectionObserver

This is not properly monospaced. It should use Bikeshed's `{{IntersectionObserver}}` syntax

> Set _this_ internal `callback` slot
> If _target_ is in `observationTargets` slot

- Slots should either be written as just links, or should use the _this_.`[[callback]]` notation. They should not be monospaced if they're not using the `[[callback]]` notation.
- Concretely, slot references should be either "_this_'s callback" / "_this_'s observation targets" or "_this_.`[[callback]]`" / "_this_.`[[observationTargets]]`". The examples above, and many more, are grammatically confusing. (Whose observationTargets slot?)

> disconnect() 1)

The numbered list for disconnect() uses the wrong style

> _target_.content width.

There is no property of target named "content width". You should instead say "_target_'s content width".

> !=

This should be "is not equal to"

> is an HTML element
> is an SVGGraphicsElement 

This should be `is an {{HTMLElement}}` and `is a {{SVGGraphicsElement}}`

> `**not**`

Should use `<em>` or `<strong>`, not double-asterisks

> content width spec does not mention how multi-column layout affects content box.

This is lowercase but starts a sentence. Also I don't think that's the name of the spec.

> getComputedStyle(`Element`).width

`getComputedStyle(Element)` will throw, since `Element` is a function, not an element. You should also write this in code font. Probably it should be `getComputedStyle(element).width` or `getComputedStyle(target).width`.

> Let depth be the depth passed in.

You should state the parameters an algorithm takes up front, instead of making them the first step in the algorithm. For example, see https://dom.spec.whatwg.org/#concept-event-create

> Clear observer’s activeTargets, and skippedTargets
> If observation.isActive() is true
> Let shallowestTargetDepth be ∞

Missing periods

> return false.
> broadcast active observations delivers all active observations in a document

Missing capitalizations

> entry.contentRect.width.

See #49; you need to refer to _entry_'s content rect's width dimension instead of trying to access public properties. The public properties will be broken e.g. if someone does `Object.defineProperty(DOMRectReadOnly.prototype, "width", { get() { throw new Error("boo"); } })`.

> For each fully active Document in docs, run the following steps for that Document and its browsing contentx:

Misspelled browsing context

Every list item is miscapitalized and missing periods.

> repeat while (document has active observations)

No need for the parenthesis

> Deliver Resize Loop Error
> CSS Definitions
> content rect
> Internal Slot Definitions
> ResizeObserver Lifetime
> External Spec Integrations
> HTML Processing Model: Event Loop

Most sections of the spec use sentence case, but these either use all-uppercase or all-lowercase. Best to make them consistent with the rest.

**Comment by atotic** [comment]
Handing off spec to greg and csswg. Tried to fix some of these..
