### ISSUE TITLE
Question: one vs multiple ResizeObserver(s) performance

### ISSUE THREAD

**Issue by mina-skunk** [WICG/ResizeObserver#59]
The `ResizeObserver` has an `observe()` method and an `unobserve()` method. This seems to encourage having one `ResizeObserver` instance and observing and unobserving different elements as needed with logic in the callback to handle each entity. Is there any performance implications of doing this vs instantiating multiple `ResizeObserver`s for observing different elements or groups of elements?

**Comment by eeeps** [comment]
The recommended pattern is to use one `ResizeObserver` to observe multiple elements. @atotic looked into the performance gains of using one-vs-many ROs – they are dramatic: https://groups.google.com/a/chromium.org/d/msg/blink-dev/z6ienONUb5A/F5-VcUZtBAAJ
