### ISSUE TITLE
Add snappedConcreteObjectSize to ResizeObserverEntry, to support precise canvas rendering

### ISSUE THREAD

**Issue by chrishtr** [WICG/ResizeObserver#61]
Right now, ResizeObserver can report the contentRect size of laid-out elements, but it cannot
report the final size of the painted content after pixel-snapping. This is necessary to support
perfect rendering of Canvas content. See https://github.com/KhronosGroup/WebGL/issues/2460
for one example.

I propose adding a field called snappedConcreteObjectSize to ResizeObserverEntry (https://wicg.github.io/ResizeObserver/#resize-observer-entry-interface) that has
this information.

This field is already defined for the CSS paint API here:
https://www.w3.org/TR/css-paint-api-1/#drawing-an-image

snappedConcreteObjectSize is defined as actual device pixel dimensions of the drawing surface of the element, divided by the
devicePixelRatio.

**Comment by kenrussell** [comment]
This would be fantastic! It would solve longstanding problems in the WebGL specification like https://github.com/KhronosGroup/WebGL/issues/2460 .

**Comment by atotic** [comment]
Discussion moved to csswg: https://github.com/w3c/csswg-drafts/issues/3326
