### ISSUE TITLE
The second argument for the callback

### ISSUE THREAD

**Issue by sag1v** [WICG/ResizeObserver#63]
As per the [spec](https://wicg.github.io/ResizeObserver/#resize-observer-callback), the callback can get a second argument of `ResizeObserver observer`.  
As far as i know, this is the current instance of the `ResizeObserver` (correct me if i'm wrong).
Is there a common use case for the instance inside the callback?
The only one i could think of is if i want to `observe` or `disconnect` inside the callback but that's a strange use case anyway. 

Just want to be sure i'm not missing anything.

**Comment by HolgerJeromin** [comment]
You could `observe` or `unobserve` other elements in the callback, too.

**Comment by sag1v** [comment]
@HolgerJeromin Thanks, Yeah i wrote it in my question.
 > The only one i could think of is if i want to observe or disconnect inside the callback but that's a strange use case anyway.
