### ISSUE TITLE
SVG elements are not observable

### ISSUE THREAD

**Issue by atotic** [WICG/ResizeObserver#9]
Currently, SVG elements are not observable, and get no ResizeNotifications. They do not have a contentBox.

Internally, Chrome has SVGGraphicsElements which do have a bounding box, whose changes we can watch.

I would like to leave SVG elements as unobservable for simplicity. Any objections?

**Comment by tabatkins** [comment]
`<svg>` elements embedded in HTML _do_ work, right? If not, they need to.

I'd prefer that SVG elements worked here too. It's weird when parts of the platform don't interoperate properly, and SVG is basically just HTML's set of drawing elements, alongside `<canvas>`.

**Comment by atotic** [comment]
`<svg>` does work, but not `<rect>`. It is a consequence of SVG DOM being different from HTML DOM, 

As a developer, I expect SVG and HTML Elements to behave similarly, but according to spec they are different. SVGElements do not have a contentBox, which is what we are observing.

I read the spec looking for anything like a "contentBox", and could not find it.

I agree that as a developer I'd expect it to work. If adding this to spec, what do you suggest SVG contentBox be?

As a developer, I feel that SVG should be observable. As a spec writer, browser implementor, I am weary of walking into an undefined behavior land...

**Comment by tabatkins** [comment]
The correct box for SVG elements is basically always their decorated bounding box (which includes their fill/stroke/markers).

**Comment by atotic** [comment]
Is "decorated bounding box" specified anywhere I can reference from my spec? I know what you mean, but in the specs I like to reference the original definition.

**Comment by atotic** [comment]
SVG observation added to spec.
